//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soap_client_dotnet.BanqueWSService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="BanqueWS", ConfigurationName="soap_client_dotnet.BanqueWSService.BanqueWS")]
    public interface BanqueWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="BanqueWS/BanqueWS/ConversationEuroToDhRequest", ReplyAction="BanqueWS/BanqueWS/ConversationEuroToDhResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<soap_client_dotnet.BanqueWSService.ConversationEuroToDhResponse> ConversationEuroToDhAsync(soap_client_dotnet.BanqueWSService.ConversationEuroToDhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BanqueWS/BanqueWS/getCompteRequest", ReplyAction="BanqueWS/BanqueWS/getCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<soap_client_dotnet.BanqueWSService.getCompteResponse> getCompteAsync(soap_client_dotnet.BanqueWSService.getCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BanqueWS/BanqueWS/getAllComptesRequest", ReplyAction="BanqueWS/BanqueWS/getAllComptesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<soap_client_dotnet.BanqueWSService.getAllComptesResponse> getAllComptesAsync(soap_client_dotnet.BanqueWSService.getAllComptesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversationEuroToDh", WrapperNamespace="BanqueWS", IsWrapped=true)]
    public partial class ConversationEuroToDhRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="BanqueWS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code;
        
        public ConversationEuroToDhRequest()
        {
        }
        
        public ConversationEuroToDhRequest(int code)
        {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversationEuroToDhResponse", WrapperNamespace="BanqueWS", IsWrapped=true)]
    public partial class ConversationEuroToDhResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="BanqueWS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public ConversationEuroToDhResponse()
        {
        }
        
        public ConversationEuroToDhResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="BanqueWS")]
    public partial class compte
    {
        
        private int codeField;
        
        private int soldeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int solde
        {
            get
            {
                return this.soldeField;
            }
            set
            {
                this.soldeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompte", WrapperNamespace="BanqueWS", IsWrapped=true)]
    public partial class getCompteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="BanqueWS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code;
        
        public getCompteRequest()
        {
        }
        
        public getCompteRequest(int code)
        {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompteResponse", WrapperNamespace="BanqueWS", IsWrapped=true)]
    public partial class getCompteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="BanqueWS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public soap_client_dotnet.BanqueWSService.compte @return;
        
        public getCompteResponse()
        {
        }
        
        public getCompteResponse(soap_client_dotnet.BanqueWSService.compte @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllComptes", WrapperNamespace="BanqueWS", IsWrapped=true)]
    public partial class getAllComptesRequest
    {
        
        public getAllComptesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllComptesResponse", WrapperNamespace="BanqueWS", IsWrapped=true)]
    public partial class getAllComptesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="BanqueWS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public soap_client_dotnet.BanqueWSService.compte[] @return;
        
        public getAllComptesResponse()
        {
        }
        
        public getAllComptesResponse(soap_client_dotnet.BanqueWSService.compte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface BanqueWSChannel : soap_client_dotnet.BanqueWSService.BanqueWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class BanqueWSClient : System.ServiceModel.ClientBase<soap_client_dotnet.BanqueWSService.BanqueWS>, soap_client_dotnet.BanqueWSService.BanqueWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BanqueWSClient() : 
                base(BanqueWSClient.GetDefaultBinding(), BanqueWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BanqueWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BanqueWSClient(EndpointConfiguration endpointConfiguration) : 
                base(BanqueWSClient.GetBindingForEndpoint(endpointConfiguration), BanqueWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BanqueWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BanqueWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BanqueWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BanqueWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BanqueWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soap_client_dotnet.BanqueWSService.ConversationEuroToDhResponse> soap_client_dotnet.BanqueWSService.BanqueWS.ConversationEuroToDhAsync(soap_client_dotnet.BanqueWSService.ConversationEuroToDhRequest request)
        {
            return base.Channel.ConversationEuroToDhAsync(request);
        }
        
        public System.Threading.Tasks.Task<soap_client_dotnet.BanqueWSService.ConversationEuroToDhResponse> ConversationEuroToDhAsync(int code)
        {
            soap_client_dotnet.BanqueWSService.ConversationEuroToDhRequest inValue = new soap_client_dotnet.BanqueWSService.ConversationEuroToDhRequest();
            inValue.code = code;
            return ((soap_client_dotnet.BanqueWSService.BanqueWS)(this)).ConversationEuroToDhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soap_client_dotnet.BanqueWSService.getCompteResponse> soap_client_dotnet.BanqueWSService.BanqueWS.getCompteAsync(soap_client_dotnet.BanqueWSService.getCompteRequest request)
        {
            return base.Channel.getCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<soap_client_dotnet.BanqueWSService.getCompteResponse> getCompteAsync(int code)
        {
            soap_client_dotnet.BanqueWSService.getCompteRequest inValue = new soap_client_dotnet.BanqueWSService.getCompteRequest();
            inValue.code = code;
            return ((soap_client_dotnet.BanqueWSService.BanqueWS)(this)).getCompteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<soap_client_dotnet.BanqueWSService.getAllComptesResponse> soap_client_dotnet.BanqueWSService.BanqueWS.getAllComptesAsync(soap_client_dotnet.BanqueWSService.getAllComptesRequest request)
        {
            return base.Channel.getAllComptesAsync(request);
        }
        
        public System.Threading.Tasks.Task<soap_client_dotnet.BanqueWSService.getAllComptesResponse> getAllComptesAsync()
        {
            soap_client_dotnet.BanqueWSService.getAllComptesRequest inValue = new soap_client_dotnet.BanqueWSService.getAllComptesRequest();
            return ((soap_client_dotnet.BanqueWSService.BanqueWS)(this)).getAllComptesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BanqueWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BanqueWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8089/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BanqueWSClient.GetBindingForEndpoint(EndpointConfiguration.BanqueWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BanqueWSClient.GetEndpointAddress(EndpointConfiguration.BanqueWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            BanqueWSPort,
        }
    }
}
